digiminds/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dracrawla.urls')),
]

dracrawla/urls.py
from django.contrib import admin
from django.urls import path, re_path

from dracrawla import views
from django.conf import settings
from django.conf.urls.static import static




app_name = 'dracrawla'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MyIndexView.as_view(), name="my_index_web"),
    path('login', views.Login.as_view(), name="login_view"),
    path('register', views.Register.as_view(), name="register_view"),
    path('manage-accounts_superadmin', views.ManageAccounts_superadmin.as_view(), name="manageaccounts_view_superadmin"),
    path('manage-accounts', views.ManageAccounts.as_view(), name="manageaccounts_view"),
    path('login-history', views.LoginHistory.as_view(), name="loginhistory_view"),
    path('create-announcements', views.CreateAnnouncements.as_view(), name="createannouncements_view"),
    path('display-announcements', views.DisplayAnnouncements.as_view(), name="displayannouncements_view"),
    path('historical-data', views.HistoricalData.as_view(), name="historicaldata_view"),
    path('logout', views.logout, name="logout_view"),
    path('logoutadmin', views.logoutadmin, name="logoutadmin_view"),

    path('main', views.MainPok.as_view(), name="main_view"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dracrawla/models.py
from django.db import models
# from datetime import datetime


# Create your models here.

class Account(models.Model):
    uid = models.BigAutoField(primary_key = True)
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)    
    email = models.CharField(max_length = 50, unique = True)
    username = models.CharField(max_length = 100, unique = True)
    password = models.CharField(max_length = 200) 
    timein = models.DateTimeField(auto_now_add=True)
    timeout = models.DateTimeField(blank = True, null=True)

class SuperAdmin(models.Model):
    aid = models.AutoField(primary_key = True)
    username = models.CharField(max_length = 50)
    password = models.CharField(max_length = 30)

# class LogHistory(Account):
#     timein = models.DateField(default=datetime.now(),blank=True)
#     timeout = models.DateField(blank=True, null=True)

class Annoucement(models.Model):
    id = models.AutoField(primary_key = True)
    title = models.CharField(max_length=1000)
    content = models.CharField(max_length=1000)#longtext,
    date = models.DateField()
    isApproved = models.BooleanField(default=True)

class Drainage(models.Model):
    did = models.AutoField(primary_key = True)
    size = models.IntegerField()
    shape = models.CharField(max_length=50)
    waterlevel = models.IntegerField()
    blockage = models.BooleanField(default=False)
    # long = models.DecimalField(max_digits=, decimal_places=)
    # lat = models.DecimalField(max_digits=, decimal_places=)

dracrawla/forms.py
from django import forms
from .models import *
from django import forms
from .models import *



class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields= '__all__'

    # def clean_username(self):
    #     username = self.cleaned_data['username']
    #     if Account.objects.filter(username=username).exists():
    #         raise forms.ValidationError(u'Username %s is already in use.' % username)
    #     return username

class AnnouncementForm(forms.ModelForm):
    class Meta:
        model = Annoucement
        fields= '__all__'

class DrainageForm(forms.ModelForm):
    class Meta:
        model = Drainage
        fields= '__all__'

dracrawla/views.py
# from asyncio.windows_events import NULL
from contextlib import nullcontext
from django.views.generic import View, TemplateView
from dracrawla.forms import AccountForm, AnnouncementForm,DrainageForm
from dracrawla.models import Account, Annoucement, SuperAdmin, Drainage
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import HttpResponse
from django.shortcuts import redirect
from datetime import datetime
from passlib.hash import pbkdf2_sha256
from cryptography.fernet import Fernet
from django.views import static

from django.contrib import messages
# from ip2geotools.databases.noncommercial import DbIpCity


# Create your views here.
def listToString(list):
    length = len(list)
    if length == 0 :
        return ""
    elif length == 1 :
        return "{}".format(list[0])
    else:
        strings = ["{}".format(x) for x in list[:-1]]
        return "{} and {}".format(", ".join(strings), list[-1])

def logout(request):
    try:
        del request.session['usern']
        request.session.flush()
    except KeyError:
        pass
    return redirect('dracrawla:login_view')

def logoutadmin(request):
    try:
        del request.session['admin']
        request.session.flush()
    except KeyError:
        pass
    return redirect('dracrawla:login_view')

class MainPok(View):
    def get(self, request):
        context = {
            'user': {},
            'drainage': []
        }
        if 'usern' in request.session:
            current_user=request.session['usern']
            drainage = Drainage.objects.all()
            user=Account.objects.filter(username=current_user)
            context = {'user':user,
            'drainage':drainage,
                            }
        elif 'admin' in request.session:
            current_user=request.session['admin']
            puser = Account.objects.all()
            drainage = Drainage.objects.all()
            user=SuperAdmin.objects.filter(username=current_user)
            context = {'user':user,
            'drainage':drainage,
                        }
        else:
            return redirect('dracrawla:login_view');
        return render(request, 'main2.html',context)
    def post(self, request):
        print("im in outsite")
        form = DrainageForm(request.POST)        
        if form.is_valid():
            # try:
            print("im in")

            Id = request.POST.get("did")            
            drainagesize = request.POST.get("size")
            dshape = request.POST.get("shape")
            dwaterlevel = request.POST.get("waterlevel")
            if (request.POST.get("blockage") == 'on'):
                isblocked = True
            else:
                isblocked = False

            form = Drainage(did = Id, size=drainagesize, shape=dshape, waterlevel=dwaterlevel, blockage=isblocked)
            print('clicked')
            form.save()

                    
            return redirect('dracrawla:main_view')
            # except:
            #   raise Http404

        if request.method == 'POST':
            if 'BtnUpdate' in request.POST:
                print('update button clicked')

                updateid = request.POST.get("did-uid")                                                                                                                                                                                                                                                                                                                                            
                dsize = request.POST.get("drainage_size")
                dshape = request.POST.get("drainage_shape")             
                dwaterlevel = request.POST.get("drainage_waterlevel")
                if (('drainage_blockage' not in request.POST)):
                    isblockage = False
                else:
                    isblockage = True

                update_drainage = Drainage.objects.filter(did=updateid).update(size = dsize, 
                 shape=dshape, waterlevel=dwaterlevel, blockage=isblockage)
                print(update_drainage)
                print('updated')
                
            elif 'BtnDelete' in request.POST:
                print('delete button clicked')
                Did = request.POST.get("drain-did")
                announce = Drainage.objects.filter(did=Did).delete()
                print("deleted")

        return redirect('dracrawla:main_view')



class MyIndexView(View):
    def get(self, request):
        if 'usern' in request.session:
            current_user=request.session['usern']
            user=Account.objects.filter(username=current_user)
            context = {'user':user,
                        }
        elif 'admin' in request.session:
            current_user=request.session['admin']
            user=SuperAdmin.objects.filter(username=current_user)
            context = {'user':user,
                        }
            print(current_user)
        else:
            return redirect('dracrawla:login_view')
        
        return render(request, 'index.html',context)

class Login(View):

    def get(self, request):
        return render(request,'login.html')

    def post(self, request):
        if request.method == 'POST':

            username = request.POST.get("username")
            password = request.POST.get("password")
            check_admin = SuperAdmin.objects.filter(username=username, password=password)
            if check_admin:
                request.session['admin'] = username
                if SuperAdmin.objects.filter(username=username).count()>0:
                    messages.success(request, 'Superadmin access granted')    
                    return redirect('dracrawla:my_index_web')

            check_password = Account.objects.filter(username=username).values_list("password",flat=True)
            listpw = list(check_password)
            try:
                dec_password = pbkdf2_sha256.verify(password, listToString(listpw))
            except ValueError:
                pass
            check_username = Account.objects.filter(username=username)
            
            # check_user = Account.objects.filter(username=username, password=check_password)
            check_admin = SuperAdmin.objects.filter(username='superadmin', password='superadmin')
            otime = datetime.now()
            print(otime)
            updatetime = Account.objects.filter(username=username).update(timein=otime, timeout=otime)
            print(updatetime) 
            # print(dec_password)
            # print(check_user)
            # print(check_password)
            if check_username and dec_password:
                request.session['usern'] = username
                if Account.objects.filter(username=username).count()>0:  
                        messages.success(request, 'Access granted')              
                        return redirect('dracrawla:my_index_web')
            else:   
                    messages.error(request, 'Invalid username or password')
                    return redirect('dracrawla:login_view')   

        else:   

            return render(request,"register.html")  

class Register(View):
  
    def get(self, request):
        if 'usern' in request.session:
            current_user=request.session['usern']
            user=Account.objects.filter(username=current_user)
        elif 'admin' in request.session:
            current_user=request.session['admin']
            user=SuperAdmin.objects.filter(username=current_user)
            context = {'user':user,
                        }
        else:
            return redirect('dracrawla:login_view')
        context = {
                'user' : user
                }
        return render(request, 'register.html',context)
        
    def post(self, request):        
        form = AccountForm(request.POST)  

        if form.is_valid():

            Uid = request.POST.get("uid")    
            Fname = request.POST.get("first_name")      
            Lname = request.POST.get("last_name")     
            Email = request.POST.get("email")
            Username = request.POST.get("username")
            Password = request.POST.get("password")
            enc_password = pbkdf2_sha256.encrypt(Password, rounds=12000, salt_size=32)
            form = Account(uid = Uid, first_name = Fname, last_name = Lname, email = Email, username = Username, password=enc_password)
            print('clicked')
            form.save() 
            return redirect('dracrawla:login_view')

        else:
            print(form.errors)
            messages.error(request, 'Unable to add account')
            return redirect('dracrawla:register_view')



class ManageAccounts_superadmin(View):
    def get(self, request):
        if 'admin' in request.session:
            current_user=request.session['admin']
            admin=SuperAdmin.objects.filter(username=current_user)
            user = Account.objects.all()
            context = {
                'admin':admin,
                'user':user,
                        }
            print(current_user)
        else:
            return redirect('dracrawla:login_view')
        return render(request,'manage-accounts_superadmin.html', context)

    def post(self, request):
        if request.method == 'POST':
            if 'btnUpdate' in request.POST:
                print('update button clicked')
                Idn = request.POST.get("uid-uid") 
                Fname = request.POST.get("first_name")        
                Lname = request.POST.get("last_name")                                                                                                                                                                                                                                                             
                Email = request.POST.get("email-email")             
                Username = request.POST.get("user-name")

dracrawla/templates/display-announcement.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>DraCrawla</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">


  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

 <!-- fontawesome -->
 <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet">
  
  <!-- Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<link href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/datedropper.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/datedropper.js"></script>
<body>


   <!-- ======= Header ======= -->
   <header id="header" class="header-inner-pages">
    <div class="container d-flex align-items-center justify-content-lg-between">
       <a href="{% url 'dracrawla:my_index_web' %}" class="me-auto me-lg-0"><img src="{% static 'assets/img/logo-clean.png' %}" alt="" class="img-fluid" style="width: 35%;"></a>

       <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'dracrawla:my_index_web' %}">Home</a></li>
          <li class="dropdown"><a href="#"><span>{% for user in user %}<span class="fa-solid fa-user"></span>&nbsp;{{user.username}}{% endfor %}</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              {% for useradmin in user %}
              {% with sups="superadmin" %}
              {% if useradmin.username == sups %}
              <li><a href="{% url 'dracrawla:manageaccounts_view_superadmin' %}">Manage Accounts</a></li>
              {% else %}
              <li><a href="{% url 'dracrawla:manageaccounts_view' %}">Accounts </a></li>
              {% endif %}
              {% endwith %}
              {% endfor %}
              <li><a href="{% url 'dracrawla:register_view' %}">Add Accounts</a></li>
              <li><a class="nav-link scrollto" href="{% url 'dracrawla:loginhistory_view' %}">Logs</a></li>
              {% for useradmin in user %}
              {% with sups="superadmin" %}
              {% if useradmin.username == sups %}
              <li><a type="submit" name='btnLogout' class="nav-link scrollto active" href="{% url 'dracrawla:logoutadmin_view' %}">Logout</a></li>
              {% else %}
              <li><a type="submit" name='btnLogout' class="nav-link scrollto active" href="{% url 'dracrawla:logout_view' %}">Logout</a></li>
              {% endif %}
              {% endwith %}
              {% endfor %}
            </ul>
          </li>
        </ul>        
        <i class="bi bi-list mobile-nav-toggle"></i>
        
      </nav><!-- .navbar --> 
      &nbsp;&nbsp;
      <a href="{% url 'dracrawla:main_view' %}" class="get-started-btn scrollto">Get Started</a>
    </div>
  </header><!-- End Header -->








		   <!--------main-content------------->
		  
		   <div class="main-content ">
			  <div class="row ">
			    
				<div class="col-md-12 ">
				<div class="table-wrapper ">
    <div class="table-title ">
      <div class="row ">
        <div class="col-sm-6 p-0 d-flex justify-content-lg-start justify-content-center ">
          <h2 class="ml-lg-2 ">      &nbsp;&nbsp;&nbsp; View Announcements</h2>
        </div>
     
     
      </div>
    </div>
  
    <table class="table table-hover " id="bootstrap-table ">    
      
            {% for viewannouncement in viewannouncement %}
            <tr>
            
                  
                  
        
                  
                  <p><div class="alert alert-warning" role="alert" style="width:90%; padding-right: 20px;">
                    <h4 class="alert-heading">Title: {{viewannouncement.title}}</h4>
                    <p>Content: {{viewannouncement.content}}</p>
                    <hr>
                    <p class="mb-0">Published Date: {{viewannouncement.date}}</p>
                  </div>          </p>
           

    {% endfor %}  
</div>  
                </td> 
             </tr>
                      
            </tbody>
            </table>
        </div>
        </div>
    </div>
   
















  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <img src="{% static 'assets/img/logo-clean.png' %}" class="img-fluid" style="width: 75%;">
              <p>
                <br>Cebu Institute of Technology - University
              </p>
              <div class="social-links mt-3">
                <a href="https://www.facebook.com/CITUniversity/" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="https://twitter.com/cit_university" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="https://www.instagram.com/cit.university/?hl=en" class="instagram"><i class="bx bxl-instagram"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>CONTACT US</h4>
            <ul>
              <li>digiminds.support@gmail.com</li>
              <li>+63 928 421 3074</li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>RELATED PROJECTS</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">POSTE</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">CUrb Flood</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-newsletter">
            <h4>THE PROJECT</h4>
            <p>DraCrawla (Drainage Crawler Robot) is a technology development initiative create a multi-sensory input probe for drainage inspection</p>
          </div>

        </div>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/nicEdit-latest.js' %}"></script>
  <script type="text/javascript">
      bkLib.onDomLoaded(function() {
            new nicEditor().panelInstance('area1');
      });
  </script>
  <script>
  $(document).ready(function(){
     $('#date').dateDropper({
        });
    });
  </script>
</body>

</html>

dracrawla/templates/fail.html
{% for message in messages %}
    <script>                        
        Swal.fire({
                title: "Failed!",
                html: "{{ message }}",
                icon: "error",
                timer: 3e3,
                timerProgressBar: !1,
                didOpen: () => {
                    Swal.showLoading();
                    const e = Swal.getHtmlContainer().querySelector("b");
                    l = setInterval(() => {
                        e.textContent = Swal.getTimerLeft();
                    }, 100);
                },
                willClose: () => {
                    clearInterval(l);
                },
            }).then((l) => {
                l.dismiss === Swal.DismissReason.timer && console.log("I was closed by the timer");
            });
    </script>                  
{% endfor %}

dracrawla/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>DraCrawla</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <!-- <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet"> -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <!-- fontawesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <!-- sweetalert -->
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>

<body>
  {% include 'success.html' %}

  <!-- ======= Header ======= -->
  <header id="header" class="header-inner-pages">
    <div class="container d-flex align-items-center justify-content-lg-between">
       <a href="{% url 'dracrawla:my_index_web' %}" class="me-auto me-lg-0"><img src="{% static 'assets/img/logo-clean.png' %}" alt="" class="img-fluid" style="width: 35%;"></a>

       <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'dracrawla:my_index_web' %}">Home</a></li>
          <li class="dropdown"><a href="#"><span>{% for user in user %}<span class="fa-solid fa-user"></span>&nbsp;{{user.username}}{% endfor %}</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              {% for useradmin in user %}
              {% with sups="superadmin" %}
              {% if useradmin.username == sups %}
              <li><a href="{% url 'dracrawla:manageaccounts_view_superadmin' %}">Manage Accounts</a></li>
              {% else %}
              <li><a href="{% url 'dracrawla:manageaccounts_view' %}">Accounts </a></li>
              {% endif %}
              {% endwith %}
              {% endfor %}
              <li><a href="{% url 'dracrawla:register_view' %}">Add Accounts</a></li>
              <li><a class="nav-link scrollto" href="{% url 'dracrawla:loginhistory_view' %}">Logs</a></li>
              {% for useradmin in user %}
              {% with sups="superadmin" %}
              {% if useradmin.username == sups %}
              <li><a type="submit" name='btnLogout' class="nav-link scrollto active" href="{% url 'dracrawla:logoutadmin_view' %}">Logout</a></li>
              {% else %}
              <li><a type="submit" name='btnLogout' class="nav-link scrollto active" href="{% url 'dracrawla:logout_view' %}">Logout</a></li>
              {% endif %}
              {% endwith %}
              {% endfor %}
            </ul>
          </li>
        </ul>   
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
      &nbsp;&nbsp;
      <a href="{% url 'dracrawla:main_view' %}" class="get-started-btn scrollto">Get Started</a>

    </div>
  </header><!-- End Header -->

  
  <section id="hero" class="d-flex align-items-center justify-content-center">
    <div class="container position-relative text-center text-lg-start" data-aos="zoom-in" data-aos-delay="100">
      <div class="row">
        <div class="col-lg-12">
          <h1>DraCrawla: <span style="color: #000000; background-color: #ffb400;">Drainage Monitoring System</span></h1>
          <div class="main-easy col-lg-8">
              <h2 style="font-size: 18px;">A web application that shows the coordinates of the DraCrawla Robot by collecting the data sent by the sensor. This application will be a helpful tool in tracking the robot when under operation of drainage inspections.</h2>
           </div>
        </div>

      </div>
      <a href="{% url 'dracrawla:createannouncements_view' %}" class="get-started-btn scrollto">Create Announcements</a>
      <a href="{% url 'dracrawla:displayannouncements_view' %}" class="get-started-btn scrollto">View Announcements</a>

    </div>

    
    
  </section>

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <img src="{% static 'assets/img/logo-clean.png' %}" class="img-fluid" style="width: 75%;">
              <p>
                <br>Cebu Institute of Technology - University
              </p>
              <div class="social-links mt-3">
                <a href="https://www.facebook.com/CITUniversity/" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="https://twitter.com/cit_university" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="https://www.instagram.com/cit.university/?hl=en" class="instagram"><i class="bx bxl-instagram"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>CONTACT US</h4>
            <ul>
              <li>digiminds.support@gmail.com</li>
              <li>+63 928 421 3074</li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>RELATED PROJECTS</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">POSTE</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">CUrb Flood</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-newsletter">
            <h4>THE PROJECT</h4>
            <p>DraCrawla (Drainage Crawler Robot) is a technology development initiative create a multi-sensory input probe for drainage inspection</p>
          </div>

        </div>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

dracrawla/templates/success.html
{% for message in messages %}
    <script>                        
        Swal.fire({
                title: "Success!",
                html: "{{ message }}",
                icon: "success",
                timer: 3e3,
                timerProgressBar: !1,
                didOpen: () => {
                    Swal.showLoading();
                    const e = Swal.getHtmlContainer().querySelector("b");
                    l = setInterval(() => {
                        e.textContent = Swal.getTimerLeft();
                    }, 100);
                },
                willClose: () => {
                    clearInterval(l);
                },
            }).then((l) => {
                l.dismiss === Swal.DismissReason.timer && console.log("I was closed by the timer");
            });
    </script>                  
{% endfor %}